// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtbMXZXAJTkQV6qKi2aX6dSW6xbkB80S8',
    appId: '1:117867501693:web:a10305be119f2a6f733914',
    messagingSenderId: '117867501693',
    projectId: 'usedmarket-960f3',
    authDomain: 'usedmarket-960f3.firebaseapp.com',
    storageBucket: 'usedmarket-960f3.firebasestorage.app',
    measurementId: 'G-8NY5T3193D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxlsJH_bsI4JLC_LxeMsey8KA-TpukKFc',
    appId: '1:117867501693:android:5c5ce775c00355f8733914',
    messagingSenderId: '117867501693',
    projectId: 'usedmarket-960f3',
    storageBucket: 'usedmarket-960f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVwTYIyD8yixNH_wlvlfpX-nQOAF-f3g',
    appId: '1:117867501693:ios:4be3f35a9d5f684d733914',
    messagingSenderId: '117867501693',
    projectId: 'usedmarket-960f3',
    storageBucket: 'usedmarket-960f3.firebasestorage.app',
    iosBundleId: 'com.example.usedmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVwTYIyD8yixNH_wlvlfpX-nQOAF-f3g',
    appId: '1:117867501693:ios:4be3f35a9d5f684d733914',
    messagingSenderId: '117867501693',
    projectId: 'usedmarket-960f3',
    storageBucket: 'usedmarket-960f3.firebasestorage.app',
    iosBundleId: 'com.example.usedmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtbMXZXAJTkQV6qKi2aX6dSW6xbkB80S8',
    appId: '1:117867501693:web:841cbdd86ed38f68733914',
    messagingSenderId: '117867501693',
    projectId: 'usedmarket-960f3',
    authDomain: 'usedmarket-960f3.firebaseapp.com',
    storageBucket: 'usedmarket-960f3.firebasestorage.app',
    measurementId: 'G-7KQC68CFM0',
  );
}
